name: Auto PR Description

on:
  pull_request:
    types: [opened]
    
jobs:
  generate-description:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Generate PR description
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            
            // Only update if description is empty
            if (!pullRequest.body || pullRequest.body.trim() === '') {
              // Generate PR description summary
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                body: ':robot: *This PR description was automatically generated*\n\n'
                    + '## Summary\n\n'
                    + '${{ github.event.pull_request.title }}\n\n'
                    + '## Changes\n\n'
                    + '<!-- PR-ROBOT:SUMMARY -->'  // GitHub will replace this marker with the summary
              });
            }
